name: Django Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  django-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./00_fullstack_django/requirements.txt
      - name: Run Tests
        run: |
          python ./00_fullstack_django/fullstack_django/manage.py test

  docker-image:
    runs-on: ubuntu-latest
    needs: django-test

    steps:
      - uses: actions/checkout@v5

      - name: Build Docker image
        run: |
            docker build -t foxitfun/django-app ./00_fullstack_django/
            sleep 10

      - name: Run Docker Container
        run: |
            docker run -d --name django-app -p 8000:8000 foxitfun/django-app
            sleep 10
      
      
      - name: Verify container is running
        run: docker container ls | grep django-app
      
      - name: Print container logs
        run: |
          echo "::group::Container logs"
          docker logs django-app
          echo "::endgroup::"
